import product1Img1 from "../assets/products/1/1.webp";
import product1Img2 from "../assets/products/1/2.webp";
import product1Img3 from "../assets/products/1/3.webp";
import product2Img1 from "../assets/products/2/1.png";
import product2Img2 from "../assets/products/2/2.webp";
import product2Img3 from "../assets/products/2/3.webp";
import product3Img1 from "../assets/products/3/1.png";
import product3Img2 from "../assets/products/3/2.webp";
import product3Img3 from "../assets/products/3/3.webp";
import product4Img1 from "../assets/products/4/1.png";
import product4Img2 from "../assets/products/4/2.webp";
import product5Img1 from "../assets/products/5/1.png";
import product5Img2 from "../assets/products/5/2.webp";
import product6Img1 from "../assets/products/6/1.png";
import product6Img2 from "../assets/products/6/2.webp";
import product7Img1 from "../assets/products/7/1.png";
import product7Img2 from "../assets/products/7/2.webp";
import product8Img1 from "../assets/products/8/1.png";
import product8Img2 from "../assets/products/8/2.webp";
import product9Img1 from "../assets/products/9/1.png";
import product9Img2 from "../assets/products/9/2.webp";
import product10Img1 from "../assets/products/10/1.png";
import product10Img2 from "../assets/products/10/2.webp";
import product11Img1 from "../assets/products/11/1.png";
import product11Img2 from "../assets/products/11/2.webp";
import product12Img1 from "../assets/products/12/1.webp";
import product12Img2 from "../assets/products/12/2.webp";
import product13Img1 from "../assets/products/13/1.png";
import product13Img2 from "../assets/products/13/2.webp";
import product14Img1 from "../assets/products/14/1.png";
import product14Img2 from "../assets/products/14/2.webp";
import product15Img1 from "../assets/products/15/1.png";
import product15Img2 from "../assets/products/15/2.webp";
import product16Img1 from "../assets/products/16/1.png";
import product16Img2 from "../assets/products/16/2.png";
import product17Img1 from "../assets/products/17/1.png";
import product17Img2 from "../assets/products/17/2.webp";
import product18Img1 from "../assets/products/18/1.png";
import product18Img2 from "../assets/products/18/2.webp";
import product19Img1 from "../assets/products/19/1.png";
import product19Img2 from "../assets/products/19/2.webp";
import product20Img1 from "../assets/products/20/1.png";
import product20Img2 from "../assets/products/20/2.webp";
import product21Img1 from "../assets/products/21/1.png";
import product21Img2 from "../assets/products/21/2.webp";
import product22Img1 from "../assets/products/22/1.png";
import product22Img2 from "../assets/products/22/2.webp";
import product23Img1 from "../assets/products/23/1.png";
import product23Img2 from "../assets/products/23/2.webp";
import product24Img1 from "../assets/products/24/1.png";
import product24Img2 from "../assets/products/24/2.webp";

const data = [
  {
    id: 1,
    title: "Annibale Colombo Sofa",
    description:
      "The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.",
    category: "furniture",
    price: 2499.99,
    discountPercentage: 14.4,
    rating: 3.92,
    stock: 60,
    tags: ["furniture", "sofas"],
    sku: "FUR-ANN-ANN-011",
    brand: "Annibale Colombo",
    weight: 6,
    dimensions: {
      width: 12.75,
      height: 20.55,
      depth: 19.06,
    },
    warrantyInformation: "Lifetime warranty",
    shippingInformation: "Ships in 1 week",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 3,
        comment: "Very unhappy with my purchase!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Christian Perez",
        reviewerEmail: "christian.perez@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Fast shipping!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Lillian Bishop",
        reviewerEmail: "lillian.bishop@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Poor quality!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Lillian Simmons",
        reviewerEmail: "lillian.simmons@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 1,
    images: [product1Img1, product1Img2, product1Img3],
  },
  {
    id: 2,
    title: "Hammock Decoration Swing",
    description:
      "The Decoration Swing is a charming addition to your home decor. Crafted with intricate details, it adds a touch of elegance and whimsy to any room.",
    category: "home-decoration",
    price: 59.99,
    discountPercentage: 10.41,
    rating: 3.16,
    stock: 47,
    brand: "Hammock House",
    tags: ["home decor", "swing"],
    sku: "HOM-BRD-DEC-043",
    weight: 4,
    dimensions: {
      width: 23.84,
      height: 15.19,
      depth: 26.05,
    },
    warrantyInformation: "1 week warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 1,
        comment: "Would not buy again!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Daniel Cook",
        reviewerEmail: "daniel.cook@x.dummyjson.com",
      },
      {
        rating: 2,
        comment: "Poor quality!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Hunter Gordon",
        reviewerEmail: "hunter.gordon@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "Very unhappy with my purchase!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Stella Morris",
        reviewerEmail: "stella.morris@x.dummyjson.com",
      },
    ],
    returnPolicy: "90 days return policy",
    minimumOrderQuantity: 8,
    images: [product2Img1, product2Img2, product2Img3],
  },
  {
    id: 3,
    title: "Bedside Table African Cherry",
    description:
      "The Bedside Table in African Cherry is a stylish and functional addition to your bedroom, providing convenient storage space and a touch of elegance.",
    category: "furniture",
    price: 299.99,
    discountPercentage: 19.09,
    rating: 2.87,
    stock: 64,
    tags: ["furniture", "bedside tables"],
    brand: "Furniture Co.",
    sku: "FUR-FUR-BED-013",
    weight: 2,
    dimensions: {
      width: 13.47,
      height: 24.99,
      depth: 27.35,
    },
    warrantyInformation: "5 year warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Excellent quality!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Aaliyah Hanson",
        reviewerEmail: "aaliyah.hanson@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Excellent quality!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Liam Smith",
        reviewerEmail: "liam.smith@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly recommended!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Avery Barnes",
        reviewerEmail: "avery.barnes@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 3,
    images: [product3Img1, product3Img2, product3Img3],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/thumbnail.webp",
  },
  {
    id: 4,
    title: "Black Aluminium Cup",
    description:
      "The Black Aluminium Cup is a stylish and durable cup suitable for both hot and cold beverages. Its sleek black design adds a modern touch to your drinkware collection.",
    category: "kitchen-accessories",
    price: 5.99,
    discountPercentage: 15.65,
    rating: 4.46,
    stock: 75,
    brand: "Obsidian",
    tags: ["drinkware", "cups"],
    sku: "KIT-BRD-BLA-049",
    weight: 7,
    dimensions: {
      width: 5.88,
      height: 5.11,
      depth: 10.03,
    },
    warrantyInformation: "1 year warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 3,
        comment: "Very disappointed!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Alexander Hernandez",
        reviewerEmail: "alexander.hernandez@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Great value for money!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Aurora Rodriguez",
        reviewerEmail: "aurora.rodriguez@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Not worth the price!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Benjamin Foster",
        reviewerEmail: "benjamin.foster@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 48,
    images: [product4Img1, product4Img2],
  },
  {
    id: 5,
    title: "Family Tree Photo Frame",
    description:
      "The Family Tree Photo Frame is a sentimental and stylish way to display your cherished family memories. With multiple photo slots, it tells the story of your loved ones.",
    category: "home-decoration",
    price: 29.99,
    discountPercentage: 14.87,
    rating: 4.53,
    stock: 77,
    brand: "Obsidian",
    tags: ["home decor", "photo frame"],
    sku: "HOM-BRD-FAM-044",
    weight: 1,
    dimensions: {
      width: 17.27,
      height: 14.81,
      depth: 29.11,
    },
    warrantyInformation: "1 month warranty",
    shippingInformation: "Ships in 2 weeks",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Highly impressed!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Oscar Powers",
        reviewerEmail: "oscar.powers@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Excellent quality!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Austin Hudson",
        reviewerEmail: "austin.hudson@x.dummyjson.com",
      },
      {
        rating: 2,
        comment: "Very dissatisfied!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Luke Cooper",
        reviewerEmail: "luke.cooper@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 15,
    images: [product5Img1, product5Img2],
  },
  {
    id: 6,
    title: "House Showpiece Plant",
    description:
      "The House Showpiece Plant is an artificial plant that brings a touch of nature to your home without the need for maintenance. It adds greenery and style to any space.",
    category: "home-decoration",
    price: 39.99,
    discountPercentage: 7.46,
    rating: 4.67,
    stock: 28,
    brand: "Drift and Dwell",
    tags: ["home decor", "artificial plants"],
    sku: "HOM-BRD-HOU-045",
    weight: 8,
    dimensions: {
      width: 8.55,
      height: 14.62,
      depth: 17.25,
    },
    warrantyInformation: "1 year warranty",
    shippingInformation: "Ships in 1 week",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Very happy with my purchase!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Natalie Harris",
        reviewerEmail: "natalie.harris@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Poor quality!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Max Russell",
        reviewerEmail: "max.russell@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very pleased!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Nolan Gonzalez",
        reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 3,
    images: [product6Img1, product6Img2],
  },
  {
    id: 7,
    title: "Hammock Table Lamp",
    description:
      "The Table Lamp is a functional and decorative lighting solution for your living space. With a modern design, it provides both ambient and task lighting, enhancing the atmosphere.",
    category: "home-decoration",
    price: 49.99,
    discountPercentage: 7.09,
    rating: 3.55,
    stock: 9,
    brand: "Hammock House",
    tags: ["home decor", "lighting"],
    sku: "HOM-BRD-TAB-047",
    weight: 4,
    dimensions: {
      width: 8.98,
      height: 13.41,
      depth: 5.65,
    },
    warrantyInformation: "3 months warranty",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Excellent quality!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Benjamin Foster",
        reviewerEmail: "benjamin.foster@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "Would not recommend!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Sophia Jones",
        reviewerEmail: "sophia.jones@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Awesome product!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Natalie Harris",
        reviewerEmail: "natalie.harris@x.dummyjson.com",
      },
    ],
    returnPolicy: "90 days return policy",
    minimumOrderQuantity: 2,
    images: [product7Img1, product7Img2],
  },
  {
    id: 8,
    title: "Chopping Board",
    description:
      "The Chopping Board is an essential kitchen accessory for food preparation. Made from durable material, it provides a safe and hygienic surface for cutting and chopping.",
    category: "kitchen-accessories",
    price: 12.99,
    discountPercentage: 8.03,
    rating: 3.7,
    stock: 14,
    brand: "HearthWood",
    tags: ["kitchen tools", "cutting boards"],
    sku: "KIT-BRD-CHO-053",
    weight: 2,
    dimensions: {
      width: 15.6,
      height: 6.93,
      depth: 8.51,
    },
    warrantyInformation: "3 months warranty",
    shippingInformation: "Ships in 2 weeks",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Great value for money!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Xavier Wright",
        reviewerEmail: "xavier.wright@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Great value for money!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Henry Turner",
        reviewerEmail: "henry.turner@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Fast shipping!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Evelyn Walker",
        reviewerEmail: "evelyn.walker@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 5,
    images: [product8Img1, product8Img2],
  },
  {
    id: 9,
    title: "Wooden Bathroom Sink With Mirror",
    description:
      "The Wooden Bathroom Sink with Mirror is a unique and stylish addition to your bathroom, featuring a wooden sink countertop and a matching mirror.",
    category: "furniture",
    price: 799.99,
    discountPercentage: 8.8,
    rating: 3.59,
    stock: 7,
    tags: ["furniture", "bathroom"],
    brand: "Bath Trends",
    sku: "FUR-BAT-WOO-015",
    weight: 10,
    dimensions: {
      width: 7.98,
      height: 8.88,
      depth: 28.46,
    },
    warrantyInformation: "3 year warranty",
    shippingInformation: "Ships in 3-5 business days",
    availabilityStatus: "Low Stock",
    reviews: [
      {
        rating: 4,
        comment: "Fast shipping!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Logan Torres",
        reviewerEmail: "logan.torres@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very pleased!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Aria Parker",
        reviewerEmail: "aria.parker@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "Poor quality!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Dylan Wells",
        reviewerEmail: "dylan.wells@x.dummyjson.com",
      },
    ],
    returnPolicy: "60 days return policy",
    minimumOrderQuantity: 2,
    images: [product9Img1, product9Img2],
  },
  {
    id: 10,
    title: "Annibale Colombo Bed",
    description:
      "The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.",
    category: "furniture",
    price: 1899.99,
    discountPercentage: 8.57,
    rating: 4.77,
    stock: 88,
    tags: ["furniture", "beds"],
    brand: "Annibale Colombo",
    sku: "FUR-ANN-ANN-011",
    weight: 10,
    dimensions: {
      width: 28.16,
      height: 25.36,
      depth: 17.28,
    },
    warrantyInformation: "1 year warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 2,
        comment: "Would not recommend!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Christopher West",
        reviewerEmail: "christopher.west@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly impressed!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Vivian Carter",
        reviewerEmail: "vivian.carter@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Poor quality!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Mason Wright",
        reviewerEmail: "mason.wright@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 1,
    images: [product10Img1, product10Img2],
  },
  {
    id: 11,
    title: "Carbon Steel Wok",
    description:
      "The Carbon Steel Wok is a versatile cooking pan suitable for stir-frying, sautéing, and deep frying. Its sturdy construction ensures even heat distribution for delicious meals.",
    category: "kitchen-accessories",
    price: 29.99,
    discountPercentage: 6.53,
    rating: 4.05,
    stock: 40,
    brand: "HearthWood",
    tags: ["cookware", "woks"],
    sku: "KIT-BRD-CAR-052",
    weight: 2,
    dimensions: {
      width: 27.69,
      height: 7.54,
      depth: 10.11,
    },
    warrantyInformation: "2 year warranty",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Excellent quality!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Nolan Bryant",
        reviewerEmail: "nolan.bryant@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly impressed!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Luna Perez",
        reviewerEmail: "luna.perez@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very satisfied!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Noah Lewis",
        reviewerEmail: "noah.lewis@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 9,
    images: [product11Img1, product11Img2],
  },
  {
    id: 12,
    title: "Fine Mesh Strainer",
    description:
      "The Fine Mesh Strainer is a versatile tool for straining liquids and sifting dry ingredients. Its fine mesh ensures efficient filtering for smooth cooking and baking.",
    category: "kitchen-accessories",
    price: 9.99,
    discountPercentage: 3.5,
    rating: 3.04,
    stock: 85,
    brand: "HearthWood",
    tags: ["kitchen tools", "strainers"],
    sku: "KIT-BRD-FIN-057",
    weight: 9,
    dimensions: {
      width: 18.02,
      height: 13.23,
      depth: 15.92,
    },
    warrantyInformation: "1 month warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Very pleased!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Isabella Anderson",
        reviewerEmail: "isabella.anderson@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly impressed!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Aaliyah Hanson",
        reviewerEmail: "aaliyah.hanson@x.dummyjson.com",
      },
      {
        rating: 2,
        comment: "Would not recommend!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Layla Sullivan",
        reviewerEmail: "layla.sullivan@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 43,
    images: [product12Img1, product12Img2],
  },
  {
    id: 13,
    title: "GoodHomes Steel Fork",
    description:
      "The Fork is a classic utensil for various dining and serving purposes. Its durable and ergonomic design makes it a reliable choice for everyday use.",
    category: "kitchen-accessories",
    price: 3.99,
    discountPercentage: 8.07,
    rating: 3.11,
    stock: 7,
    brand: "GOODHOMES",
    tags: ["kitchen tools", "utensils"],
    sku: "KIT-BRD-FOR-058",
    weight: 9,
    dimensions: {
      width: 12.3,
      height: 25.91,
      depth: 22.57,
    },
    warrantyInformation: "No warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Highly impressed!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Elena Baker",
        reviewerEmail: "elena.baker@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very satisfied!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Avery Scott",
        reviewerEmail: "avery.scott@x.dummyjson.com",
      },
      {
        rating: 2,
        comment: "Would not buy again!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Mateo Perez",
        reviewerEmail: "mateo.perez@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 36,
    images: [product13Img1, product13Img2],
  },
  {
    id: 14,
    title: "GoodHomes Tumbler Glass",
    description:
      "The Glass is a versatile and elegant drinking vessel suitable for a variety of beverages. Its clear design allows you to enjoy the colors and textures of your drinks.",
    category: "kitchen-accessories",
    price: 4.99,
    discountPercentage: 7.92,
    rating: 4.02,
    stock: 46,
    brand: "GOODHOMES",
    tags: ["drinkware", "glasses"],
    sku: "KIT-BRD-GLA-059",
    weight: 10,
    dimensions: {
      width: 20.23,
      height: 24.56,
      depth: 26.97,
    },
    warrantyInformation: "3 year warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Very happy with my purchase!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Jackson Evans",
        reviewerEmail: "jackson.evans@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "Waste of money!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Nicholas Bailey",
        reviewerEmail: "nicholas.bailey@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very satisfied!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Nathan Reed",
        reviewerEmail: "nathan.reed@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 17,
    images: [product14Img1, product14Img2],
  },
  {
    id: 15,
    title: "Grater Black",
    description:
      "The Grater in Black is a handy kitchen tool for grating cheese, vegetables, and more. Its sleek design and sharp blades make food preparation efficient and easy.",
    category: "kitchen-accessories",
    price: 10.99,
    discountPercentage: 3.56,
    rating: 3.21,
    stock: 84,
    brand: "Obsidian",
    tags: ["kitchen tools", "graters"],
    sku: "KIT-BRD-GRA-060",
    weight: 3,
    dimensions: {
      width: 6.32,
      height: 23.11,
      depth: 24.64,
    },
    warrantyInformation: "1 month warranty",
    shippingInformation: "Ships in 1 week",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 1,
        comment: "Would not buy again!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Ella Adams",
        reviewerEmail: "ella.adams@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Not as described!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Eli Ward",
        reviewerEmail: "eli.ward@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Highly impressed!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "James Garcia",
        reviewerEmail: "james.garcia@x.dummyjson.com",
      },
    ],
    returnPolicy: "60 days return policy",
    minimumOrderQuantity: 5,
    images: [product15Img1, product15Img2],
  },
  {
    id: 16,
    title: "Ice Cube Tray",
    description:
      "The Ice Cube Tray is a practical accessory for making ice cubes in various shapes. Perfect for keeping your drinks cool and adding a fun element to your beverages.",
    category: "kitchen-accessories",
    price: 5.99,
    discountPercentage: 0.63,
    rating: 4.71,
    stock: 13,
    brand: "Obsidian",
    tags: ["kitchen tools", "ice cube trays"],
    sku: "KIT-BRD-CUB-062",
    weight: 3,
    dimensions: {
      width: 26.67,
      height: 18.14,
      depth: 5.31,
    },
    warrantyInformation: "1 month warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Awesome product!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Isaac Lawrence",
        reviewerEmail: "isaac.lawrence@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Would buy again!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Leo Rivera",
        reviewerEmail: "leo.rivera@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very pleased!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Henry Turner",
        reviewerEmail: "henry.turner@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 16,
    images: [product16Img1, product16Img2],
  },
  {
    id: 17,
    title: "GoodHomes Kitchen Knife",
    description:
      "The Knife is an essential kitchen tool for chopping, slicing, and dicing. Its sharp blade and ergonomic handle make it a reliable choice for food preparation.",
    category: "kitchen-accessories",
    price: 14.99,
    discountPercentage: 18.86,
    rating: 3.26,
    stock: 7,
    brand: "GOODHOMES",
    tags: ["kitchen tools", "cutlery"],
    sku: "KIT-BRD-KNI-064",
    weight: 3,
    dimensions: {
      width: 25.19,
      height: 18.52,
      depth: 20.5,
    },
    warrantyInformation: "1 month warranty",
    shippingInformation: "Ships in 1 week",
    availabilityStatus: "Low Stock",
    reviews: [
      {
        rating: 2,
        comment: "Very disappointed!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Aaliyah Martinez",
        reviewerEmail: "aaliyah.martinez@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Fast shipping!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Addison Wright",
        reviewerEmail: "addison.wright@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very pleased!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Mateo Nguyen",
        reviewerEmail: "mateo.nguyen@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 50,
    images: [product17Img1, product17Img2],
  },
  {
    id: 18,
    title: "Mug Tree Stand",
    description:
      "The Mug Tree Stand is a stylish and space-saving solution for organizing your mugs. Keep your favorite mugs easily accessible and neatly displayed in your kitchen.",
    category: "kitchen-accessories",
    price: 15.99,
    discountPercentage: 9.25,
    rating: 2.64,
    stock: 88,
    brand: "Obsidian",
    tags: ["kitchen tools", "organization"],
    sku: "KIT-BRD-TRE-067",
    weight: 3,
    dimensions: {
      width: 18.99,
      height: 27.14,
      depth: 27.29,
    },
    warrantyInformation: "1 year warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 1,
        comment: "Very unhappy with my purchase!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Bella Grant",
        reviewerEmail: "bella.grant@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Highly recommended!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Paisley Bell",
        reviewerEmail: "paisley.bell@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Fast shipping!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "David Martinez",
        reviewerEmail: "david.martinez@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 45,
    images: [product18Img1, product18Img2],
  },
  {
    id: 19,
    title: "Non-Stick Pan",
    description:
      "The Pan is a versatile and essential cookware item for frying, sautéing, and cooking various dishes. Its non-stick coating ensures easy food release and cleanup.",
    category: "kitchen-accessories",
    price: 24.99,
    discountPercentage: 3,
    rating: 2.79,
    stock: 90,
    brand: "Obsidian",
    tags: ["cookware", "pans"],
    sku: "KIT-BRD-PRD-068",
    weight: 8,
    dimensions: {
      width: 17.14,
      height: 21.7,
      depth: 25.75,
    },
    warrantyInformation: "1 year warranty",
    shippingInformation: "Ships in 3-5 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Highly impressed!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Michael Johnson",
        reviewerEmail: "michael.johnson@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly recommended!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Adrian Flores",
        reviewerEmail: "adrian.flores@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Not as described!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Nicholas Bailey",
        reviewerEmail: "nicholas.bailey@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 17,
    images: [product19Img1, product19Img2],
  },
  {
    id: 20,
    title: "Blossom & Bowl Plates",
    description:
      "The Plate is a classic and essential dishware item for serving meals. Its durable and stylish design makes it suitable for everyday use or special occasions.",
    category: "kitchen-accessories",
    price: 3.99,
    discountPercentage: 7.31,
    rating: 3.65,
    stock: 66,
    brand: "Blossom & Bowl",
    tags: ["dinnerware", "plates"],
    sku: "KIT-BRD-PLA-069",
    weight: 4,
    dimensions: {
      width: 16.46,
      height: 5.39,
      depth: 13.15,
    },
    warrantyInformation: "1 year warranty",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 3,
        comment: "Disappointing product!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Mia Miller",
        reviewerEmail: "mia.miller@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Great product!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Henry Adams",
        reviewerEmail: "henry.adams@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Excellent quality!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Nora Russell",
        reviewerEmail: "nora.russell@x.dummyjson.com",
      },
    ],
    returnPolicy: "90 days return policy",
    minimumOrderQuantity: 6,
    images: [product20Img1, product20Img2],
  },
  {
    id: 21,
    title: "GoodHomes Silver Pot With Glass Cap",
    description:
      "The Silver Pot with Glass Cap is a stylish and functional cookware item for boiling, simmering, and preparing delicious meals. Its glass cap allows you to monitor cooking progress.",
    category: "kitchen-accessories",
    price: 39.99,
    discountPercentage: 5.7,
    rating: 3.22,
    stock: 40,
    brand: "GOODHOMES",
    tags: ["cookware", "pots"],
    sku: "KIT-BRD-SIL-071",
    weight: 7,
    dimensions: {
      width: 21.03,
      height: 11.7,
      depth: 6.69,
    },
    warrantyInformation: "1 year warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Great product!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Julian Newton",
        reviewerEmail: "julian.newton@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Excellent quality!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Noah Lewis",
        reviewerEmail: "noah.lewis@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Disappointing product!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Brayden Hill",
        reviewerEmail: "brayden.hill@x.dummyjson.com",
      },
    ],
    returnPolicy: "90 days return policy",
    minimumOrderQuantity: 10,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "9757232943842",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [product21Img1, product21Img2],
  },
  {
    id: 22,
    title: "GoodHomes Slotted Turner",
    description:
      "The Slotted Turner is a kitchen utensil designed for flipping and turning food items. Its slotted design allows excess liquid to drain, making it ideal for frying and sautéing.",
    category: "kitchen-accessories",
    price: 8.99,
    discountPercentage: 13.35,
    rating: 3.4,
    stock: 88,
    brand: "GOODHOMES",
    tags: ["kitchen tools", "turners"],
    sku: "KIT-BRD-SLO-072",
    weight: 8,
    dimensions: {
      width: 14.41,
      height: 27.15,
      depth: 14.76,
    },
    warrantyInformation: "Lifetime warranty",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 1,
        comment: "Would not recommend!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Ava Taylor",
        reviewerEmail: "ava.taylor@x.dummyjson.com",
      },
      {
        rating: 2,
        comment: "Would not recommend!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Liam Smith",
        reviewerEmail: "liam.smith@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very satisfied!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Gabriel Mitchell",
        reviewerEmail: "gabriel.mitchell@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 34,
    images: [product22Img1, product22Img2],
  },
  {
    id: 23,
    title: "Spice Rack",
    description:
      "The Spice Rack is a convenient organizer for your spices and seasonings. Keep your kitchen essentials within reach and neatly arranged with this stylish spice rack.",
    category: "kitchen-accessories",
    price: 19.99,
    discountPercentage: 12.09,
    rating: 4.87,
    stock: 79,
    brand: "Obsidian",
    tags: ["kitchen tools", "organization"],
    sku: "KIT-BRD-SPI-073",
    weight: 7,
    dimensions: {
      width: 28.06,
      height: 22.43,
      depth: 26.34,
    },
    warrantyInformation: "1 week warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Very satisfied!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Elena Baker",
        reviewerEmail: "elena.baker@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Excellent quality!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Owen Fisher",
        reviewerEmail: "owen.fisher@x.dummyjson.com",
      },
      {
        rating: 2,
        comment: "Waste of money!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Sadie Morales",
        reviewerEmail: "sadie.morales@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 18,
    images: [product23Img1, product23Img2],
  },
  {
    id: 24,
    title: "GoodHomes Steel Spoon",
    description:
      "The Spoon is a versatile kitchen utensil for stirring, serving, and tasting. Its ergonomic design and durable construction make it an essential tool for every kitchen.",
    category: "kitchen-accessories",
    price: 4.99,
    discountPercentage: 1.53,
    rating: 4.03,
    stock: 59,
    brand: "GOODHOMES",
    tags: ["kitchen tools", "utensils"],
    sku: "KIT-BRD-SPO-074",
    weight: 6,
    dimensions: {
      width: 8.49,
      height: 26.04,
      depth: 27.78,
    },
    warrantyInformation: "1 year warranty",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 3,
        comment: "Waste of money!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Jackson Evans",
        reviewerEmail: "jackson.evans@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Disappointing product!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Elena Baker",
        reviewerEmail: "elena.baker@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Awesome product!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Bella Gonzalez",
        reviewerEmail: "bella.gonzalez@x.dummyjson.com",
      },
    ],
    returnPolicy: "90 days return policy",
    minimumOrderQuantity: 15,
    images: [product24Img1, product24Img2],
  },
];

export default data;
